In [2]:
import pandas as pd
import os

In [3]:
path = r"C:\Users\Matthew Wijaya\Downloads\fertility\fertility_Diagnosis.txt"
cols = [
    "season",
    "age",
    "child_diseases",
    "accident",
    "surgical_intervention",
    "high_fevers",
    "alcohol",
    "smoking",
    "hrs_sitting",
    "diagnosis"
]

df = pd.read_csv(path, header=None, names=cols, delimiter=",")

In [28]:
df = df.iloc[3:,:]

In [4]:
df

,season,age,child_diseases,accident,surgical_intervention,high_fevers,alcohol,smoking,hrs_sitting,diagnosis
0,-0.33,0.69,0,1,1,0,0.8,0,0.88,N
1,-0.33,0.94,1,0,1,0,0.8,1,0.31,O
2,-0.33,0.50,1,0,0,0,1.0,-1,0.50,N
3,-0.33,0.75,0,1,1,0,1.0,-1,0.38,N
4,-0.33,0.67,1,1,0,0,0.8,-1,0.50,O
...,...,...,...,...,...,...,...,...,...,...
95,-1.00,0.67,1,0,0,0,1.0,-1,0.50,N
96,-1.00,0.61,1,0,0,0,0.8,0,0.50,N
97,-1.00,0.67,1,1,1,0,1.0,-1,0.31,N
98,-1.00,0.64,1,0,1,0,1.0,0,0.19,N
99,-1.00,0.69,0,1,1,0,0.6,-1,0.19,N

In [5]:
df.to_csv(r"D:\MATTHEW\UROPS\Datasets\All Datasets\Valid Datasets\Fertility.csv", index=False)

In [45]:
files = [r"C:\Users\Matthew Wijaya\Downloads\avila\avila\avila-tr.txt", r"C:\Users\Matthew Wijaya\Downloads\avila\avila\avila-ts.txt"]

df_list = [pd.read_csv(f, delimiter=',') for f in files]  # Adjust delimiter if needed
df_combined = pd.concat(df_list, ignore_index=True)  # Merge them together
column_names = [
    "intercolumnar_distance",
    "upper_margin",
    "lower_margin",
    "exploitation",
    "row_number",
    "modular_ratio",
    "interlinear_spacing",
    "weight",
    "peak_number",
    "modular_ratio_interlinear_spacing",
    'class'
]

df_combined.columns = column_names

# print(df_combined.head())
# df_combined.to_csv("combined.csv", index=False)  # Save as CSV if needed

ValueError: Length mismatch: Expected axis has 22 elements, new values have 11 elements

In [47]:
# Define column names
column_names = [
    "intercolumnar_distance",
    "upper_margin",
    "lower_margin",
    "exploitation",
    "row_number",
    "modular_ratio",
    "interlinear_spacing",
    "weight",
    "peak_number",
    "modular_ratio_interlinear_spacing",
    'class'
]

# List of file paths
files = [r"C:\Users\Matthew Wijaya\Downloads\avila\avila\avila-tr.txt", r"C:\Users\Matthew Wijaya\Downloads\avila\avila\avila-ts.txt"]

# Read and concatenate all files
df_list = [pd.read_csv(f, delimiter=',', header=None, dtype=str) for f in files]
df = pd.concat(df_list, ignore_index=True)

# Assign column names
df.columns = column_names

# Convert numeric columns to integers
df.iloc[:, :-1] = df.iloc[:, :-1].astype(int)

# Display first few rows
print(df.head())

# Save to CSV (optional)
# df.to_csv(r"D:\MATTHEW\UROPS\Datasets\All Datasets\Valid Multiclass Datasets\merged_vehicle_silhouettes.csv", index=False)

ValueError: invalid literal for int() with base 10: '0.266074'

In [35]:
df_combined = df_combined.drop(columns = ['date'])

In [7]:
df_combined

,95,48,83,178,72,10,162,42,20,159,...,36,199,73.1,40,127,189,401,6.1,200,204
0,91.0,41.0,84.0,141.0,57.0,9.0,149.0,45.0,19.0,143.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,104.0,50.0,106.0,209.0,66.0,10.0,207.0,32.0,23.0,158.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93.0,41.0,82.0,159.0,63.0,9.0,144.0,46.0,19.0,143.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,85.0,44.0,70.0,205.0,103.0,52.0,149.0,45.0,19.0,144.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,107.0,57.0,106.0,172.0,50.0,6.0,255.0,26.0,28.0,169.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832,NaN,NaN,NaN,NaN,72.0,NaN,169.0,NaN,20.0,NaN,...,39.0,183.0,64.0,40.0,134.0,200.0,422.0,7.0,188.0,195.0
833,NaN,NaN,NaN,NaN,72.0,NaN,159.0,NaN,20.0,NaN,...,46.0,163.0,66.0,43.0,159.0,173.0,368.0,1.0,186.0,197.0
834,NaN,NaN,NaN,NaN,70.0,NaN,222.0,NaN,25.0,NaN,...,54.0,222.0,67.0,30.0,173.0,228.0,721.0,3.0,187.0,201.0
835,NaN,NaN,NaN,NaN,66.0,NaN,135.0,NaN,18.0,NaN,...,36.0,146.0,58.0,50.0,124.0,155.0,270.0,0.0,190.0,195.0
836,NaN,NaN,NaN,NaN,73.0,NaN,120.0,NaN,17.0,NaN,...,36.0,123.0,55.0,56.0,128.0,140.0,212.0,1.0,186.0,190.0

In [40]:
df_combined.to_csv(r'D:\MATTHEW\UROPS\Datasets\All Datasets\Valid Datasets\sepsis.csv', index=False)

In [33]:
paths = [
    r'C:\Users\Matthew Wijaya\Downloads\harth\harth'
]

# List to hold all DataFrames
dataframes = []

# Loop through each path and read the .txt files
for path in paths:
    for file in os.listdir(path):
        if not file.endswith('.txt'):
            file_path = os.path.join(path, file)
            # Read the .txt file
            df = pd.read_csv(file_path, delimiter = ',')  # Change delimiter if needed
            dataframes.append(df)

# columns = [
#     "Time in seconds",
#     "Acceleration reading in G for frontal axis",
#     "Acceleration reading in G for vertical axis",
#     "Acceleration reading in G for lateral axis",
#     "Id of antenna reading sensor",
#     "Received signal strength indicator (RSSI)",
#     "Phase",
#     "Frequency",
#     "Label"
# ]
# Combine all DataFrames into one
combined_df = pd.concat(dataframes, ignore_index=True)
# combined_df.columns = columns

In [38]:
combined_df

           back_x    back_y    back_z   thigh_x   thigh_y   thigh_z  label
0       -0.760242  0.299570  0.468570 -5.092732 -0.298644  0.709439      6
1       -0.530138  0.281880  0.319987  0.900547  0.286944  0.340309      6
2       -1.170922  0.186353 -0.167010 -0.035442 -0.078423 -0.515212      6
3       -0.648772  0.016579 -0.054284 -1.554248 -0.950978 -0.221140      6
4       -0.355071 -0.051831 -0.113419 -0.547471  0.140903 -0.653782      6
...           ...       ...       ...       ...       ...       ...    ...
6461323 -1.012939 -0.110840 -0.218994 -0.970215 -0.313232  0.124268      3
6461324 -0.979492 -0.089355 -0.216553 -0.966553 -0.234619  0.113770      3
6461325 -0.969971 -0.057861 -0.204590 -0.997803 -0.097656  0.065186      3
6461326 -1.001953 -0.029785 -0.234863 -1.000000 -0.145996  0.061523      3
6461327 -1.015381 -0.030762 -0.218262 -1.000244 -0.305420  0.076904      3

[6461328 rows x 7 columns]

In [37]:
combined_df = combined_df.iloc[:,:-2]

In [39]:
combined_df.to_csv(r'D:\MATTHEW\UROPS\Datasets\All Datasets\Valid Multiclass Datasets\HARTH.csv', index=False)